print("Suma",3+4)
print("Resta",3-4)
print("Multiplicacion",3*4)
print("Modulo",3%4)
print("Division",3/4)
print("Potencia",3**4)
print("Division entera",3//4)

print('Nombre:','José Andrés Chairez Contreras')
print('Familia','Ezequiel Chairez Fernandez','Martha Elena Contreras')
print('Pais','México')
print('I am enjoying 30 days of python')
print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['Asabeneh','Python', 'Finland']))
print(type({'name':'Andres', 'age': 18}))
print(type({'Father name':'Ezequiel Chairez Fernandez', 'mother name':'Martha Elena Contreras'}))
print(type({'Country name':'Mexico'}))
